<?php

namespace AppBundle\Repository;

/**
 * FraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisRepository extends \Doctrine\ORM\EntityRepository
{
    public function statcongatt()
    {
        
        return $this->createQueryBuilder('cg')
        ->select(' COUNT(cg.retour) as retour')
       ->where('cg.retour = 0')
       ->getQuery()
       ->getScalarResult();
    }

    public function statcongacc()
    {
        
        return $this->createQueryBuilder('cg')
        ->select(' COUNT(cg.retour) as retour')
       ->where('cg.retour = 1')
       ->getQuery()
       ->getScalarResult();
    }
    public function statcongruf()
    {
        
        return $this->createQueryBuilder('cg')
        ->select(' COUNT(cg.retour) as retour')
       ->where('cg.retour = 2')
       ->getQuery()
       ->getScalarResult();
    }

    public function statcongTotal()
    {
        
        return $this->createQueryBuilder('cg')
        ->select(' COUNT(cg.retour) as retourtotal')
       ->getQuery()
       ->getScalarResult();
    }

    public function searchcong($poste,$status)
    {
        
        return $this->createQueryBuilder('cr')
        ->select('cr')
       ->where('cr.poste =:poste')
       ->andWhere('cr.retour =:status')
       ->setParameter('status', $status)     
       ->setParameter('poste', $poste) 
       ->getQuery()
       ->getScalarResult();
    }
}
