app_convention:
    resource: "@AppBundle/Controller/ConventionController.php"
    type:     annotation

planing:
    resource: "@PlaningBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"